---
- name: Configure
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Set provider
    set_fact:
      provider: gcp

- name: Provision
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Provision benchmark
    include_role:
      name: "{{ provider }}"
    vars:
      stage: CREATE
      machine_type: "{{ machine_type }}"
  - name: Add key to ssh-agent
    shell: ssh-add id_ed25519
  - git:
      repo: 'https://github.com/w3f/polkadot-module-benchmarking.git'
      dest: roles/substrate_benchmarks

- name: Wait for system ready
  hosts: benchmark
  gather_facts: no
  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:

- name: Run Benchmark
  hosts: benchmark
  gather_facts: yes
  tasks:
  - ping:
  - include_role:
      name: substrate-benchmarks
    vars:
      scope: "{{ scope }}"

- name: Clean
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: destroy instance
    include_role:
      name: "{{ provider }}"
    vars:
      stage: DESTROY
