---
# vars file for gcp
gcp_project:  "{{ lookup('env', 'GCP_PROJECT') | default('polkadot-benchmarks') }}"
gcp_cred_file: "{{ set_gcp_cred_file | default('credentials.json') }}"
gcp_cred_content: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS_CONTENT') }}"
gcp_cred_kind: serviceaccount
region: "{{ lookup('env', 'REGION') | default('europe-west6') }}"

machine_type: "{{ set_machine_type | default('n1-standard-1') }}"
instance_name: "gcp-benchmark-{{ machine_type }}-{{ 100 | random }}"
zone: '{{ region }}-a'
image: "{{ set_image | default('projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts') }}"
